C_SOURCES += kernel/kernel.c kernel/gdt.c kernel/paging.c kernel/idt.c kernel/pic.c kernel/isr.c kernel/tss.c kernel/cmdline.c kernel/util.c kernel/pit.c kernel/malloc.c kernel/sysenter.c
ASM_SOURCES += kernel/machineasm.S kernel/traps.S kernel/halt.S
